version: '2'
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ltf-pages:
    container_name: ltf-pages
    image: seals.azurecr.io/ltf-pages:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:pages.learntofly.global"

  ltf-admin-web:
    container_name: ltf-admin-web
    image: willguitaradmfar/ltf-admin-web:latest
    restart: always
    environment:
      SED_ORKI_SERVER_ENDPOINT: "https:\\/\\/ltf-admin-api.devmania.com.br"
    labels:
      - "traefik.frontend.rule=Host:adm.learntofly.global"

  ltf-admin-api:
    container_name: adm-api
    image: willguitaradmfar/ltf-admin-api:latest
    restart: always
    environment:
      JWT_IAT: "604800"
      PORT: "3000"
      MONGO_USER: "mongo_user"
      MONGO_PASS: "admin123"
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      MONGO_DATABASE: "myapp"
      REDIS_HOST: "redis"
      MQTT_HOST: "mqtt"
      AMQP_HOST: "rabbitmq"
      WAIT_FOR_HOSTS: "rabbitmq:5672"
      P19_HOST: "https://ltf-api.devmania.com.br"
    labels:
      - "traefik.frontend.rule=Host:adm-api.learntofly.global"

  ltf-client-web:
    container_name: calendar
    image: seals.azurecr.io/ltf-client-web:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:calendar.learntofly.global"

  ltf-server:
    container_name: calendar-api
    image: seals.azurecr.io/ltf-server:latest
    restart: always
    environment:
      GOOGLE_CLIENT_ID: "362454021622-jtg3mhn85oqapio7j700scto9328ojun.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "OBwDW6NbLUqmMcaxCcdc8Ojg"
      GOOGLE_CALLBACK_REDIRECT: "https://ltf-api.devmania.com.br/api/auth/google/callback"
      MONGO_URI: ""
      MONGO_USER: "mongo_user"
      MONGO_PASS: "admin123"
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      MONGO_DATABASE: "myapp"
      REDIS_HOST: "redis"
      MQTT_HOST: "mqtt"
      LTF_BACK_HOST: "https://ltf-api.devmania.com.br"
      LTF_FRONT_HOST: "https://ltf.devmania.com.br"
      WAIT_FOR_HOSTS: "redis:6379;mongo:27017"
    labels:
      - "traefik.frontend.rule=Host:calendar-api.learntofly.global"

  redis:
    image: redis
    restart: always

  mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=myapp
      - MONGODB_APPLICATION_USER=mongo_user
      - MONGODB_APPLICATION_PASS=admin123
    restart: always
    volumes:
      - /var/lib/mongodb:/data/db

  mqtt:
    image: eclipse-mosquitto
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
  cron-index:
    image: lodatol/cron
    restart: always
    environment:
      CRON_ENTRY: "* * * * * wget -O /dev/null http://ltf-server:3000/api/cron/tick"