version: '2'
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ltf-pages:
    container_name: ltf-pages
    image: seals.azurecr.io/ltf-pages:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:pages.learntofly.global"

  ltf-admin-web:
    container_name: ltf-admin-web
    image: willguitaradmfar/ltf-admin-web:latest
    restart: always
    environment:
      SED_ORKI_SERVER_ENDPOINT: "http:\\/\\/adm-api.learntofly.global"
    labels:
      - "traefik.frontend.rule=Host:adm.learntofly.global"

  ltf-admin-api:
    container_name: ltf-admin-api
    image: willguitaradmfar/ltf-admin-api:latest
    restart: always
    environment:
      JWT_IAT: "604800"
      PORT: "3000"
      MONGO_USER: "mongo_user"
      MONGO_PASS: "admin123"
      MONGO_HOST: "172.31.21.200"
      MONGO_PORT: "27017"
      MONGO_DATABASE: "myapp"
      REDIS_HOST: "172.31.21.200"
      MQTT_HOST: "172.31.21.200"
      AMQP_HOST: "172.31.21.200"
      WAIT_FOR_HOSTS: "172.31.21.200:5672;172.31.21.200:27017;172.31.21.200:6379;172.31.21.200:1883"
      P19_HOST: "http://calendar-api.learntofly.global"
    labels:
      - "traefik.frontend.rule=Host:adm-api.learntofly.global"

  ltf-client-web:
    container_name: ltf-client-web
    image: seals.azurecr.io/ltf-client-web:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:calendar.learntofly.global"

  ltf-server:
    container_name: ltf-server
    image: seals.azurecr.io/ltf-server:latest
    restart: always
    environment:
      GOOGLE_CLIENT_ID: "362454021622-jtg3mhn85oqapio7j700scto9328ojun.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "OBwDW6NbLUqmMcaxCcdc8Ojg"
      GOOGLE_CALLBACK_REDIRECT: "http://calendar-api.learntofly.global/api/auth/google/callback"
      MONGO_URI: ""
      MONGO_USER: "mongo_user"
      MONGO_PASS: "admin123"
      MONGO_HOST: "172.31.21.200"
      MONGO_PORT: "27017"
      MONGO_DATABASE: "myapp"
      REDIS_HOST: "172.31.21.200"
      MQTT_HOST: "172.31.21.200"
      AMQP_HOST: "172.31.21.200"
      LTF_BACK_HOST: "http://calendar-api.learntofly.global"
      LTF_FRONT_HOST: "http://calendar.learntofly.global"
      WAIT_FOR_HOSTS: "172.31.21.200:5672;172.31.21.200:27017;172.31.21.200:6379;172.31.21.200:1883"
    labels:
      - "traefik.frontend.rule=Host:calendar-api.learntofly.global"
  cron-index:
    image: lodatol/cron
    restart: always
    environment:
      CRON_ENTRY: "* * * * * wget -O /dev/null http://ltf-server:3000/api/cron/tick"