version: '2'
services:  
  redis:
    image: redis
    network_mode: host
    restart: always

  mongo:
    image: aashreys/mongo-auth:latest
    network_mode: host
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=myapp
      - MONGODB_APPLICATION_USER=mongo_user
      - MONGODB_APPLICATION_PASS=admin123
    restart: always
    volumes:
      - /var/lib/mongodb:/data/db
      - /tmp/backup:/backup

  mqtt:
    image: eclipse-mosquitto
    network_mode: host
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    network_mode: host
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
      
  minio:
    image: minio/minio 
    restart: always
    command: ["server", "/data"]
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "admin123"
  
  
